name: Deploy on staging
on:
  push:
    branches: [ development ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name : Deploying everything to the staging cluster
    steps:
      - run: |
          echo ${{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo screts.KNOWN_HOSTS &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key ubuntu@ec2-43-204-235-94.ap-south-1.compute.amazonaws.com 
          cd nextjs_ci_cd
          pnpm install
          pnpm run build 
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server